QESRC_DIR = upflib
PNAME = qepy_upflib
QEPY_LIBS = -L$(PYBUILDDIR) -lqepy_utilxlib
QEPY_INCS = -I. -I$(QEDIR)/$(QESRC_DIR) -I$(PYBUILDDIR)/utilxlib -I$(QEDIR)/UtilXlib

QEPY_OBJS = 

QEPY_PROG_OBJS = 

QE_OBJS = uspp.o \
uspp_param.o

LIB_OBJS_TEMP = atom.o \
atomic_number.o \
atwfc_mod.o \
beta_mod.o \
casino_pp.o \
dom.o \
dqvan2.o \
dylmr2.o \
gen_us_dj.o \
gen_us_dy.o \
gth.o \
init_us_0.o \
init_us_1.o \
init_us_2_acc.o \
init_us_b0.o \
paw_variables.o \
pseudo_types.o \
qrad_mod.o \
qvan2.o \
radial_grids.o \
read_cpmd.o \
read_fhi.o \
read_ncpp.o \
read_ps.o \
read_psml.o \
read_upf_new.o \
read_upf_v1.o \
read_uspp.o \
rhoat_mod.o \
rhoc_mod.o \
simpsn.o \
sph_bes.o \
sph_ind.o \
spinor.o \
splinelib.o \
upf_auxtools.o \
upf_const.o \
upf_error.o \
upf_invmat.o \
upf_io.o \
upf_ions.o \
upf_kinds.o \
upf_parallel_include.o \
upf_params.o \
upf_spinorb.o \
upf_to_internal.o \
upf_utils.o \
uspp.o \
uspp_param.o \
vloc_mod.o \
write_upf_new.o \
wxml.o \
xmltools.o \
ylmr2.o \
ylmr2_gpu.o

include ../make.qepy.inc
include ../make.depend
