QESRC_DIR = LR_Modules
PNAME = qepy_lr_modules
QEPY_LIBS = -L$(PYBUILDDIR) $(MODS_PW)
QEPY_INCS = -I. -I$(QEDIR)/$(QESRC_DIR) $(INCS_MODS_PW) $(INCS_MODS_PW_QE)

QEPY_OBJS = 

QEPY_PROG_OBJS = 

QE_OBJS = 

LIB_OBJS_TEMP = Coul_cut_2D_ph.o \
adddvepsi_us.o \
adddvhubscf.o \
adddvscf.o \
addusdbec.o \
addusdbec_nc.o \
addusldos.o \
apply_dpot.o \
apply_dpot_mod.o \
apply_trev.o \
c_bands_ph.o \
ccg_psi.o \
ccgsolve_all.o \
cft_wave.o \
cg_psi.o \
cgsolve_all.o \
ch_psi_all.o \
ch_psi_all_complex.o \
check_q_points_sym.o \
compute_vsgga.o \
dfpt_kernels.o \
dfpt_tetra_mod.o \
dfpt_type.o \
dgradcorr.o \
dnonloccorr.o \
dnsq_scf.o \
dv_of_drho.o \
dv_rVV10.o \
dv_vdW_DF.o \
dynmat_sub.o \
efermi_shift.o \
h_prec.o \
h_prec_freq.o \
incdrhoscf_mod.o \
lanczos_nonhermitian.o \
lanczos_nonhermitian_c.o \
lanczos_pseudohermitian.o \
lanczos_pseudohermitian_c.o \
localdos.o \
lr_addusddens.o \
lr_dot.o \
lr_dot_magnons.o \
lr_nc_mag.o \
lr_orthoUwfc.o \
lr_restart.o \
lr_sm1_psi.o \
lr_sym_mod.o \
lr_sym_paw.o \
lr_two_chem.o \
lrcom.o \
mix_pot.o \
mode_group.o \
newdq.o \
non_scf_ph.o \
orthogonalize.o \
orthogonalize_omega.o \
psymdvscf.o \
qdipol_cryst.o \
qpoint.o \
response_kernels.o \
set_dbecsum_nc.o \
set_int3_nc.o \
set_intq_nc.o \
set_kplusq_nc.o \
set_small_group_of_q.o \
setqmod.o \
setup_alpha_pv.o \
setup_dgc.o \
setup_dmuxc.o \
setup_nbnd_occ.o \
setup_nscf.o \
sgam_lr.o \
smallgq.o \
star_q.o \
sym_def.o \
sym_dmag.o \
sym_dns.o \
symdvscf.o \
twochem_postproc_dfpt.o

include ../make.qepy.inc
include ../make.depend
